<!DOCTYPE html>
<html lang="fr">
<head>
  <meta charset="UTF-8">
  <title>HASH</title>
  <link rel="stylesheet" href="css/style.css">
</head>
<body>
  <header>
    <h1>DOUDI HASH</h1>
  </header>
  <main>

    <form method="post">
      <input type="text" name="pass" placeholder="placez votre mot de passe à hasher ici ..." ><br><br>
      <input type="submit" value="HASHER">
    </form>

    <h2>
      <?php echo($reponse); ?>
    </h2>

  </main>
  <footer>
    <?php echo($aideCode); ?>
  </footer>
</body>
</html>
